// AUTO-GENERATED by scripts/build-brand-media.js — do not edit by hand.
// Every scraped brand image, copied into /public and measured, so brand pages can
// render each one at its true aspect ratio without cropping.

export type BrandImage = { src: string; width: number; height: number };

export const BRAND_MEDIA: Record<string, BrandImage[]> = {
  "mast-masala": [
    {
      "src": "/images/brands/mast-masala/02-chole-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/04-sambhar-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/05-shahi-chicken-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/07-chicken-tandoori-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/09-pav-bhaji-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/10-biryani-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/11-amchur-powder.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/14-coriander-cumin-powder.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/15-biryani-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/16-jeera-powder.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/17-pani-puri-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/18-coriander-powder.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/21-red-chilli-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/22-turmeric-powder.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/25-hing.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/27-rajshahi-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/28-meat-masala.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/mast-masala/10-th-guru-nanak-jayanti.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/mast-masala/happy-makar-sankrant.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/mast-masala/happy-pongal.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/mast-masala/mast-masala-dashera-2.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/mast-masala/mast-masala-dhanteras-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/mast-masala/mast-masala-oct-18-post.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/mast-masala/mast-masala-oct-19-post.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/mast-masala/mast-masala-oct-21-post.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/mast-masala/mast-masala-oct-22-post.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/mast-masala/mast-masala-gandhi-jayanti.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/mast-masala/reach-growth-8.png",
      "width": 469,
      "height": 498
    },
    {
      "src": "/images/brands/mast-masala/engagement-8.png",
      "width": 473,
      "height": 490
    },
    {
      "src": "/images/brands/mast-masala/ctrleft-4.png",
      "width": 474,
      "height": 430
    },
    {
      "src": "/images/brands/mast-masala/retension-3.png",
      "width": 471,
      "height": 431
    }
  ],
  "intellve": [
    {
      "src": "/images/brands/intellve/chatgpt-image-dec-27-2025-05-06-39-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/intellve/dhanteras-2.jpeg",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/intellve-bhai-dooj.jpg",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/onam.jpg",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/post-04-durga-puja-1.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/post-11.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/post-13.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/post-14.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/post-7.jpg",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/post-8.jpg",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/static-04.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/static-06.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/static-07.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/static-08-1.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/static-09.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/static-10.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/static-14.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/static-15.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/static-16.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/static-9.png",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/intellve/dussera.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/intellve/gandhi-jayanti.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/intellve/guru-nanak-jayanti.jpeg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/intellve/ambedkar-jayanti-intellve.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/intellve/earth-day-intellve.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/intellve/independence-day.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/intellve/raksha-bandhan.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/intellve/reach-growth-7.png",
      "width": 467,
      "height": 472
    },
    {
      "src": "/images/brands/intellve/reach-growth.png",
      "width": 467,
      "height": 472
    },
    {
      "src": "/images/brands/intellve/ctr2-1.png",
      "width": 473,
      "height": 457
    },
    {
      "src": "/images/brands/intellve/ctr2.png",
      "width": 473,
      "height": 457
    },
    {
      "src": "/images/brands/intellve/engagement-7.png",
      "width": 462,
      "height": 455
    },
    {
      "src": "/images/brands/intellve/engamenrt2.png",
      "width": 462,
      "height": 452
    },
    {
      "src": "/images/brands/intellve/retension-2.png",
      "width": 463,
      "height": 441
    }
  ],
  "kunuts": [
    {
      "src": "/images/brands/kunuts/ramdan-2x-1.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/kunuts/chatgpt-image-dec-27-2025-05-24-47-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/kunuts/health-benefits-of-pistachios.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/holi.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-14-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-7.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-jan-13.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-jan-3.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-jan-4.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-jan-6.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-jan-makarsankrat-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-jan-makarsankrat.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-jan-republic-day.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-jan-republic-day-1-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-jan-2psd.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/kunuts-jan.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/kunuts/engagement-1.png",
      "width": 468,
      "height": 452
    },
    {
      "src": "/images/brands/kunuts/reach-growth-1.png",
      "width": 466,
      "height": 446
    },
    {
      "src": "/images/brands/kunuts/crt-left.png",
      "width": 468,
      "height": 399
    },
    {
      "src": "/images/brands/kunuts/retention-3.png",
      "width": 470,
      "height": 396
    }
  ],
  "salus": [
    {
      "src": "/images/brands/salus/dsc0189-1.jpg",
      "width": 1600,
      "height": 2282
    },
    {
      "src": "/images/brands/salus/sa-4152-live-3.jpg",
      "width": 1600,
      "height": 1649
    },
    {
      "src": "/images/brands/salus/7155-10.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/salus/7155-7.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/salus/456193014-2192862997737420-8031508299174057732-n.jpg",
      "width": 1440,
      "height": 1440
    },
    {
      "src": "/images/brands/salus/56089-1.jpg",
      "width": 1600,
      "height": 1067
    },
    {
      "src": "/images/brands/salus/56089-3.jpg",
      "width": 1600,
      "height": 1067
    },
    {
      "src": "/images/brands/salus/sa-7153-bgd.jpg",
      "width": 1600,
      "height": 1000
    },
    {
      "src": "/images/brands/salus/chatgpt-image-dec-30-2025-09-55-20-pm.png",
      "width": 1536,
      "height": 1024
    },
    {
      "src": "/images/brands/salus/chatgpt-image-jan-4-2026-08-55-21-am.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/salus/13-1.jpg",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/salus/16-2.jpg",
      "width": 1080,
      "height": 1440
    },
    {
      "src": "/images/brands/salus/17-1.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/salus/sa-4152-live-1-1.jpg",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/salus/salus-9.jpg",
      "width": 700,
      "height": 1794
    },
    {
      "src": "/images/brands/salus/2-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/431977276-410283718245931-7764317246885861589-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/433478734-366351463041248-825631383532726654-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/436283118-1533709947360122-9198187085610752614-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/437296980-963829161518959-6682349479197223728-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/437939287-444412791420947-1581008568433222134-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/437981279-7324738997621909-1183900633170419247-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/440373174-961749555089587-7992986260996373891-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/441181954-750928500201159-5840406652411348696-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/447789938-452501517382539-2549015562025870240-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/455307251-871122814874747-7740840006228908689-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/salus-may-grid-12-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/salus/1s9a0446.jpg",
      "width": 1000,
      "height": 1000
    },
    {
      "src": "/images/brands/salus/fhs26-hd3-02.jpg",
      "width": 749,
      "height": 1124
    },
    {
      "src": "/images/brands/salus/7159-4.jpg",
      "width": 800,
      "height": 800
    },
    {
      "src": "/images/brands/salus/7159-6.jpg",
      "width": 800,
      "height": 800
    },
    {
      "src": "/images/brands/salus/7159-7.jpg",
      "width": 800,
      "height": 800
    },
    {
      "src": "/images/brands/salus/salus-1.jpg",
      "width": 700,
      "height": 693
    },
    {
      "src": "/images/brands/salus/salus-8.jpg",
      "width": 700,
      "height": 467
    },
    {
      "src": "/images/brands/salus/salus-8-1.jpg",
      "width": 430,
      "height": 733
    },
    {
      "src": "/images/brands/salus/salus-6.jpg",
      "width": 430,
      "height": 700
    },
    {
      "src": "/images/brands/salus/engagement-2.png",
      "width": 462,
      "height": 459
    },
    {
      "src": "/images/brands/salus/reach-growth-2.png",
      "width": 464,
      "height": 452
    },
    {
      "src": "/images/brands/salus/ctrleft-1.png",
      "width": 463,
      "height": 429
    },
    {
      "src": "/images/brands/salus/retention-4.png",
      "width": 465,
      "height": 427
    },
    {
      "src": "/images/brands/salus/salus-2.jpg",
      "width": 430,
      "height": 430
    }
  ],
  "monarch": [
    {
      "src": "/images/brands/monarch/chatgpt-image-dec-27-2025-05-38-53-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/monarch/chatgpt-image-dec-30-2025-09-43-03-pm.png",
      "width": 1536,
      "height": 1024
    },
    {
      "src": "/images/brands/monarch/1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/10.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/11.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/12.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/2.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/3-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/4-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/468322917-18107859313445274-2901932152859157014-n.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/5.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/6.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/7.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/8.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/9.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/monarch/436270261-962201035644999-8047582674078374948-n.jpg",
      "width": 720,
      "height": 720
    },
    {
      "src": "/images/brands/monarch/436346202-1265801647713538-6708095825783625845-n.jpg",
      "width": 720,
      "height": 720
    },
    {
      "src": "/images/brands/monarch/441129253-460025499780541-4898027462062335074-n.jpg",
      "width": 720,
      "height": 720
    },
    {
      "src": "/images/brands/monarch/441175069-1697447383996963-5303440128693367193-n.jpg",
      "width": 720,
      "height": 720
    },
    {
      "src": "/images/brands/monarch/447582014-365123279919267-1632428410918691261-n.jpg",
      "width": 720,
      "height": 720
    },
    {
      "src": "/images/brands/monarch/452870056-2161826644182312-5928892124035476037-n.jpg",
      "width": 720,
      "height": 720
    },
    {
      "src": "/images/brands/monarch/455224616-476757474990504-8533215241120221454-n.jpg",
      "width": 720,
      "height": 720
    },
    {
      "src": "/images/brands/monarch/455728884-406592845331978-1057737521858925783-n.jpg",
      "width": 720,
      "height": 720
    },
    {
      "src": "/images/brands/monarch/457127450-1702378390539490-2901588802450952950-n.jpg",
      "width": 720,
      "height": 720
    },
    {
      "src": "/images/brands/monarch/reach-growth-3.png",
      "width": 458,
      "height": 474
    },
    {
      "src": "/images/brands/monarch/engagement-3.png",
      "width": 460,
      "height": 468
    },
    {
      "src": "/images/brands/monarch/ctr-left-1.png",
      "width": 459,
      "height": 447
    },
    {
      "src": "/images/brands/monarch/rentention.png",
      "width": 458,
      "height": 446
    }
  ],
  "rapoo": [
    {
      "src": "/images/brands/rapoo/11-1.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/rapoo/chatgpt-image-dec-30-2025-10-52-38-pm.png",
      "width": 1536,
      "height": 1024
    },
    {
      "src": "/images/brands/rapoo/mt760l-1.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/rapoo/v500-pro.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/rapoo/vt9pro.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/rapoo/copy-of-04-1.jpg",
      "width": 1200,
      "height": 1200
    },
    {
      "src": "/images/brands/rapoo/copy-of-07.jpg",
      "width": 1200,
      "height": 1200
    },
    {
      "src": "/images/brands/rapoo/copy-of-09.jpg",
      "width": 1200,
      "height": 1200
    },
    {
      "src": "/images/brands/rapoo/copy-of-10-1.jpg",
      "width": 1200,
      "height": 1200
    },
    {
      "src": "/images/brands/rapoo/10-static.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo/copy-of-02-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo/copy-of-03.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo/copy-of-11.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo/copy-of-12.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo/copy-of-13-1-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo/mousepad.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo/engagement-4.png",
      "width": 690,
      "height": 398
    },
    {
      "src": "/images/brands/rapoo/reach-growth-4.png",
      "width": 652,
      "height": 402
    },
    {
      "src": "/images/brands/rapoo/retention-1.png",
      "width": 689,
      "height": 342
    },
    {
      "src": "/images/brands/rapoo/ctrleft-2.png",
      "width": 664,
      "height": 340
    }
  ],
  "rapoo-middle-east": [
    {
      "src": "/images/brands/rapoo-middle-east/11-1.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/rapoo-middle-east/12-2.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/rapoo-middle-east/4-2.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/rapoo-middle-east/6-1.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/rapoo-middle-east/7-1.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/rapoo-middle-east/rapoo-1-2x.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/rapoo-middle-east/rapoo-7-2x.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/rapoo-middle-east/chatgpt-image-dec-28-2025-08-46-44-pm.png",
      "width": 1536,
      "height": 1024
    },
    {
      "src": "/images/brands/rapoo-middle-east/01.jpg",
      "width": 1200,
      "height": 1200
    },
    {
      "src": "/images/brands/rapoo-middle-east/02.jpg",
      "width": 1200,
      "height": 1200
    },
    {
      "src": "/images/brands/rapoo-middle-east/04.jpg",
      "width": 1200,
      "height": 1200
    },
    {
      "src": "/images/brands/rapoo-middle-east/1-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/10-2.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/10-static.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/11-static-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/12-static-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/12-static.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/14-static.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/2-2.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/3-2.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/4-static-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/5-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/5-static-1.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/5-static-2.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/6-static.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/8-2.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/laser-pen.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/mouse-keyboard-headset.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/mousepad.jpg",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/rapoo-middle-east/reach-growth-5.png",
      "width": 788,
      "height": 552
    },
    {
      "src": "/images/brands/rapoo-middle-east/engagement-5.png",
      "width": 750,
      "height": 551
    },
    {
      "src": "/images/brands/rapoo-middle-east/ctr-left-2.png",
      "width": 771,
      "height": 482
    },
    {
      "src": "/images/brands/rapoo-middle-east/retention-2.png",
      "width": 731,
      "height": 473
    }
  ],
  "furnishing-home": [
    {
      "src": "/images/brands/furnishing-home/bhaidooj.png",
      "width": 1600,
      "height": 2000
    },
    {
      "src": "/images/brands/furnishing-home/564987481-18063087149576460-6542216695873398226-n.jpg",
      "width": 1440,
      "height": 1800
    },
    {
      "src": "/images/brands/furnishing-home/dhanteras.jpeg",
      "width": 1280,
      "height": 1600
    },
    {
      "src": "/images/brands/furnishing-home/chatgpt-image-dec-27-2025-09-44-17-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/furnishing-home/chatgpt-image-dec-28-2025-07-34-33-pm.png",
      "width": 1536,
      "height": 1024
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-1.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-10.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-11.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-13.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-2.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-3-1.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-3.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-4-1.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-5.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-6-1.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-6.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-7.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/furnishing-home-cc-8.png",
      "width": 1080,
      "height": 1350
    },
    {
      "src": "/images/brands/furnishing-home/freepik-generate-this-type-for-image-img1-with-a-beautiful-5.png",
      "width": 960,
      "height": 1088
    },
    {
      "src": "/images/brands/furnishing-home/freepik-close-up-shots-59138.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-generate-diiferent-angles-and-beautiful-close-up-s-5.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-generate-diiferent-angles-and-beautiful-close-up-s-5.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-generate-diiferent-angles-and-beautiful-close-up-s-5.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-generate-diiferent-angles-and-beautiful-close-up-s-5.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-generate-diiferent-angles-and-beautiful-close-up-s-5.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-generate-diiferent-angles-and-beautiful-close-up-s-5.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-generate-diiferent-angles-and-beautiful-close-up-s-5.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-generate-diiferent-angles-and-beautiful-close-up-s-5.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-gnenerate-this-type-if-image-img1-with-the-use-of-59.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-gnenerate-this-type-if-image-img1-with-the-use-of-59.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/freepik-gnenerate-this-type-if-image-img1-with-the-use-of-59.png",
      "width": 832,
      "height": 1248
    },
    {
      "src": "/images/brands/furnishing-home/engagement-6.png",
      "width": 694,
      "height": 497
    },
    {
      "src": "/images/brands/furnishing-home/reach-growth-6.png",
      "width": 680,
      "height": 494
    },
    {
      "src": "/images/brands/furnishing-home/ctrleft-3.png",
      "width": 687,
      "height": 343
    },
    {
      "src": "/images/brands/furnishing-home/retension-1.png",
      "width": 688,
      "height": 341
    }
  ],
  "secure-my-shop": [
    {
      "src": "/images/brands/secure-my-shop/christmas-reelsize3.png",
      "width": 1080,
      "height": 1920
    },
    {
      "src": "/images/brands/secure-my-shop/newyear-resizee1.png",
      "width": 1080,
      "height": 1920
    },
    {
      "src": "/images/brands/secure-my-shop/newyear-resizee2.png",
      "width": 1080,
      "height": 1920
    },
    {
      "src": "/images/brands/secure-my-shop/chatgpt-image-dec-28-2025-05-07-50-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/secure-my-shop/18.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/19-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/21-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/25-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/26.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/28-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/slide1-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/slide1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/slide2-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/slide2.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/slide3-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/slide3.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/slide4-1.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/slide4.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/slide5.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/slide6.png",
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/images/brands/secure-my-shop/reach-growth.png",
      "width": 467,
      "height": 472
    },
    {
      "src": "/images/brands/secure-my-shop/ctr2.png",
      "width": 473,
      "height": 457
    },
    {
      "src": "/images/brands/secure-my-shop/engamenrt2.png",
      "width": 462,
      "height": 452
    },
    {
      "src": "/images/brands/secure-my-shop/retension-4.png",
      "width": 463,
      "height": 441
    }
  ],
  "icici": [
    {
      "src": "/images/brands/icici/chatgpt-image-jan-4-2026-04-17-35-pm.png",
      "width": 1536,
      "height": 1024
    },
    {
      "src": "/images/brands/icici/chatgpt-image-jan-4-2026-04-20-32-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/icici/4.jpeg",
      "width": 1005,
      "height": 1280
    },
    {
      "src": "/images/brands/icici/6-1.jpeg",
      "width": 1005,
      "height": 1280
    },
    {
      "src": "/images/brands/icici/7-1.jpeg",
      "width": 1005,
      "height": 1280
    },
    {
      "src": "/images/brands/icici/1.jpeg",
      "width": 768,
      "height": 1280
    },
    {
      "src": "/images/brands/icici/2.jpeg",
      "width": 768,
      "height": 1280
    },
    {
      "src": "/images/brands/icici/5-1.jpeg",
      "width": 768,
      "height": 1280
    },
    {
      "src": "/images/brands/icici/5.jpeg",
      "width": 768,
      "height": 1280
    },
    {
      "src": "/images/brands/icici/3-1.jpeg",
      "width": 590,
      "height": 1280
    }
  ],
  "godrej": [
    {
      "src": "/images/brands/godrej/whatsapp-image-2026-01-04-at-9-55-12-am-3.jpeg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/godrej/whatsapp-image-2026-01-04-at-9-55-12-am.jpeg",
      "width": 1600,
      "height": 1600
    },
    {
      "src": "/images/brands/godrej/whatsapp-image-2026-01-04-at-9-55-12-am-2-1.jpeg",
      "width": 1500,
      "height": 1500
    },
    {
      "src": "/images/brands/godrej/whatsapp-image-2026-01-04-at-9-55-12-am-2.jpeg",
      "width": 1500,
      "height": 1500
    },
    {
      "src": "/images/brands/godrej/whatsapp-image-2026-01-04-at-9-55-13-am.jpeg",
      "width": 1500,
      "height": 1500
    },
    {
      "src": "/images/brands/godrej/chatgpt-image-jan-3-2026-01-15-35-pm.png",
      "width": 1536,
      "height": 1024
    },
    {
      "src": "/images/brands/godrej/chatgpt-image-jan-3-2026-12-44-08-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/godrej/chatgpt-image-jan-3-2026-12-46-00-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/godrej/chatgpt-image-jan-3-2026-12-47-13-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/godrej/chatgpt-image-jan-3-2026-12-48-38-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/godrej/chatgpt-image-jan-3-2026-12-50-16-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/godrej/chatgpt-image-jan-3-2026-12-51-55-pm.png",
      "width": 1024,
      "height": 1536
    },
    {
      "src": "/images/brands/godrej/whatsapp-image-2026-01-04-at-9-55-12-am-1-1.jpeg",
      "width": 611,
      "height": 611
    },
    {
      "src": "/images/brands/godrej/whatsapp-image-2026-01-04-at-9-55-12-am-1.jpeg",
      "width": 611,
      "height": 611
    },
    {
      "src": "/images/brands/godrej/godrej.png",
      "width": 500,
      "height": 500
    },
    {
      "src": "/images/brands/godrej/reach-growth.png",
      "width": 467,
      "height": 472
    },
    {
      "src": "/images/brands/godrej/ctr2.png",
      "width": 473,
      "height": 457
    },
    {
      "src": "/images/brands/godrej/engamenrt2.png",
      "width": 462,
      "height": 452
    },
    {
      "src": "/images/brands/godrej/retension-4.png",
      "width": 463,
      "height": 441
    }
  ]
};

export const getBrandMedia = (slug: string): BrandImage[] => BRAND_MEDIA[slug] ?? [];
