# -*- coding: utf-8 -*-
# Regenerate lib/brandMedia.ts directly from the (already-deduped) files in
# public/images/brands/<slug>/. Used after dedupe-perceptual.py so the manifest
# reflects exactly what's on disk, without re-copying from client-archives.
import os, json, hashlib, io
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), "..", "public", "images", "brands")
OUT = os.path.join(os.path.dirname(__file__), "..", "lib", "brandMedia.ts")

manifest = {}
for slug in sorted(os.listdir(ROOT)):
    d = os.path.join(ROOT, slug)
    if not os.path.isdir(d):
        continue
    seen_hash = set()
    entries = []
    for name in sorted(os.listdir(d)):
        f = os.path.join(d, name)
        if not os.path.isfile(f):
            continue
        if not name.lower().endswith((".jpg", ".jpeg", ".png", ".webp")):
            continue
        try:
            with Image.open(f) as im:
                w, h = im.size
        except Exception:
            continue
        if not w or not h:
            continue
        if w < 300 and h < 300:      # skip tiny icons/favicons
            continue
        digest = hashlib.md5(open(f, "rb").read()).hexdigest()
        if digest in seen_hash:      # byte-identical safety net
            continue
        seen_hash.add(digest)
        entries.append({"src": f"/images/brands/{slug}/{name}", "width": w, "height": h})
    entries.sort(key=lambda e: -(e["width"] * e["height"]))
    manifest[slug] = entries
    print(f"{slug}: {len(entries)} images")

header = (
    "// AUTO-GENERATED by scripts/build-brand-media.js — do not edit by hand.\n"
    "// Every scraped brand image, copied into /public and measured, so brand pages can\n"
    "// render each one at its true aspect ratio without cropping.\n\n"
    "export type BrandImage = { src: string; width: number; height: number };\n\n"
    "export const BRAND_MEDIA: Record<string, BrandImage[]> = "
    + json.dumps(manifest, indent=2)
    + ";\n\n"
    "export const getBrandMedia = (slug: string): BrandImage[] => BRAND_MEDIA[slug] ?? [];\n"
)
with io.open(OUT, "w", encoding="utf-8", newline="\n") as fp:
    fp.write(header)
print("\nWrote", OUT)
